<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@820.vd1a_6cc65ef33">
  <node class="cps.n.StepAtomNode" plugin="workflow-cps@2725.v7b_c717eb_12ce">
    <parentIds>
      <string>12</string>
    </parentIds>
    <id>13</id>
    <descriptorId>org.jenkinsci.plugins.workflow.steps.durable_task.ShellStep</descriptorId>
  </node>
  <actions>
    <cps.a.ArgumentsActionImpl plugin="workflow-cps@2725.v7b_c717eb_12ce">
      <arguments>
        <entry>
          <string>script</string>
          <string>sshpass -p ${PASS} ssh -o StrictHostKeyChecking=no hidraxos@192.168.1.115 &apos;cd /home/hidraxos/Desktop/private &amp;&amp; git commit -am Thu Jul 21 14:26:27 UTC 2022&apos;</string>
        </entry>
      </arguments>
      <sensitiveVariables>
        <string>PASS</string>
      </sensitiveVariables>
      <isUnmodifiedBySanitization>false</isUnmodifiedBySanitization>
    </cps.a.ArgumentsActionImpl>
    <wf.a.TimingAction plugin="workflow-api@1164.v760c223ddb_32">
      <startTime>1658413589454</startTime>
    </wf.a.TimingAction>
    <s.a.LogStorageAction/>
    <wf.a.ErrorAction plugin="workflow-api@1164.v760c223ddb_32">
      <error class="hudson.AbortException">
        <detailMessage>script returned exit code 128</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.handleExit(DurableTaskStep.java:664)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:610)</trace>
          <trace>org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:554)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>