<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@820.vd1a_6cc65ef33">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@2706.v71dd22b_c5a_a_2">
    <parentIds>
      <string>26</string>
    </parentIds>
    <id>27</id>
    <startId>18</startId>
  </node>
  <actions>
    <wf.a.BodyInvocationAction plugin="workflow-api@1153.vb_912c0e47fb_a_"/>
    <wf.a.TimingAction plugin="workflow-api@1153.vb_912c0e47fb_a_">
      <startTime>1654543411966</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@1153.vb_912c0e47fb_a_">
      <error class="org.jenkinsci.plugins.workflow.steps.FlowInterruptedException" plugin="workflow-step-api@625.vd896b_f445a_f8">
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.interrupt(CpsFlowExecution.java:1130)</trace>
          <trace>org.jenkinsci.plugins.workflow.job.WorkflowRun$2.lambda$interrupt$0(WorkflowRun.java:397)</trace>
          <trace>jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions>
          <java.lang.InterruptedException>
            <stackTrace>
              <trace>java.base/java.lang.Object.wait(Native Method)</trace>
              <trace>hudson.remoting.Request.call(Request.java:177)</trace>
              <trace>hudson.remoting.Channel.call(Channel.java:999)</trace>
              <trace>hudson.FilePath.act(FilePath.java:1194)</trace>
              <trace>hudson.FilePath.act(FilePath.java:1183)</trace>
              <trace>hudson.FilePath.archive(FilePath.java:515)</trace>
              <trace>hudson.FilePath.archive(FilePath.java:494)</trace>
              <trace>org.jenkinsci.plugins.workflow.flow.StashManager.stash(StashManager.java:126)</trace>
              <trace>org.jenkinsci.plugins.workflow.support.steps.stash.StashStep$Execution.run(StashStep.java:119)</trace>
              <trace>org.jenkinsci.plugins.workflow.support.steps.stash.StashStep$Execution.run(StashStep.java:107)</trace>
              <trace>org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)</trace>
              <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
              <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
              <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
              <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
              <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
            </stackTrace>
            <suppressedExceptions class="empty-list"/>
          </java.lang.InterruptedException>
        </suppressedExceptions>
        <result>
          <name>ABORTED</name>
          <ordinal>4</ordinal>
          <color>ABORTED</color>
          <completeBuild>false</completeBuild>
        </result>
        <causes class="java.util.Arrays$ArrayList">
          <a class="jenkins.model.CauseOfInterruption-array">
            <jenkins.model.CauseOfInterruption_-UserInterruption>
              <user>hidraxos</user>
            </jenkins.model.CauseOfInterruption_-UserInterruption>
          </a>
        </causes>
        <actualInterruption>true</actualInterruption>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>